### ISSUE TITLE
启动时失败

### ISSUE THREAD

**Issue by guoxifeng** [284772894/monkeyTest#13]
======================
*** liyu 2015-01-15***
***     v1.0.0     ***
======================
---------------------------
Checking adb port...
�ɹ�: ����ֹ PID Ϊ 18412 �Ľ��̡�
adb devices
cannot connect to daemon at tcp:5037: cannot connect to 127.0.0.1:5037: 由于目标计算机积极拒绝，无法连接。 (10061)
adb -s P7CDU17B22002323 shell wm size
adb -s P7CDU17B22002323 shell cat /proc/meminfo
adb -s P7CDU17B22002323 shell cat /system/build.prop
cat: /system/build.prop: Permission denied
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\library\monkey\monkeyTest-master\monkeyTest.py", line 88, in start
    mkdirInit(devices, app, num)
  File "D:\library\monkey\monkeyTest-master\monkeyTest.py", line 54, in mkdirInit
    app[devices] = {"cpu": cpu, "men": men, "flow": flow, "battery": battery, "fps": fps, "header": get_phome(devices)}
  File "D:\library\monkey\monkeyTest-master\monkeyTest.py", line 38, in get_phome
    bg = BasePhoneMsg.get_phone_Kernel(devices)
  File "D:\library\monkey\monkeyTest-master\Base\BasePhoneMsg.py", line 68, in get_phone_Kernel
    phone_msg = getModel(devices)
  File "D:\library\monkey\monkeyTest-master\Base\BasePhoneMsg.py", line 35, in getModel
    output = subprocess.check_output(cmd).decode()
  File "C:\Program Files\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Program Files\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'adb -s P7CDU17B22002323 shell cat /system/build.prop' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/library/monkey/monkeyTest-master/monkeyTest.py", line 153, in <module>
    runnerPool()
  File "D:/library/monkey/monkeyTest-master/monkeyTest.py", line 77, in runnerPool
    pool.map(start, devices_Pool)
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command 'adb -s P7CDU17B22002323 shell cat /system/build.prop' returned non-zero exit status 1.

Process finished with exit code 1

**Comment by Louis-me** [comment]
这个应该是远程设备问题
