### ISSUE TITLE
请教报错信息～

### ISSUE THREAD

**Issue by samxupeiran** [284772894/monkeyTest#5]
hi, 我这边运行时一直报错，信息如下：
Traceback (most recent call last):
  File "monkeyTest.py", line 154, in <module>
    runnerPool()
  File "monkeyTest.py", line 77, in runnerPool
    pool.map(start, devices_Pool)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 2] No such file or directory

麻烦您知道我该如何解决吗，非常感谢～

**Comment by Louis-me** [comment]
你手动新建一个log目录，还有代码是基于py3

**Comment by samxupeiran** [comment]
手动新建log目录也还是同样的错。。我现在怀疑是不是Mac的锅～

**Comment by Louis-me** [comment]
为在BaseMonkeyConfig.py修改：
log = PATH("../Log") + "/"

应该是这里的路径问题，你试下

**Comment by Louis-me** [comment]
后续打算脱离PC，新版本有机会考虑适配mac,linux
