### ISSUE TITLE
不支持ubuntu linux平台吗？

### ISSUE THREAD

**Issue by Archer456** [284772894/monkeyTest#7]
我git clone下来源码工程  放入有相关包环境的 pycharm

右键执行monkeyTest.py   Run窗口看错误解决了几个权限问题后，发现有个强制执行
def killport():
    os.system(PATH('./kill5037.bat'))    这个win环境下的批处理。  该行无法在linux环境运行的吧。

所以一致会有如下的错误：   

/usr/bin/python3.5 /home/cmd/workspace/git/monkeyTest/monkeyTest.py
======================
/home/cmd/workspace/git/monkeyTest/kill5037.bat: 1: /home/cmd/workspace/git/monkeyTest/kill5037.bat: @echo: not found
Base Chinese.md MainActivity.java README.md img info kill5037.bat monkey.ini monkey1.apk monkeyTest.py report.xlsx liyu 2015-01-15***
Base Chinese.md MainActivity.java README.md img info kill5037.bat monkey.ini monkey1.apk monkeyTest.py report.xlsx v1.0.0 Base Chinese.md MainActivity.java README.md img info kill5037.bat monkey.ini monkey1.apk monkeyTest.py report.xlsx
/home/cmd/workspace/git/monkeyTest/kill5037.bat: 2: /home/cmd/workspace/git/monkeyTest/kill5037.bat: color: not found
======================
/home/cmd/workspace/git/monkeyTest/kill5037.bat: 3: /home/cmd/workspace/git/monkeyTest/kill5037.bat: title: not found
---------------------------
Checking adb port...
/home/cmd/workspace/git/monkeyTest/kill5037.bat: 10: /home/cmd/workspace/git/monkeyTest/kill5037.bat: Syntax error: Bad for loop variable
adb devices
adb -s 45806625 shell wm size
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/cmd/workspace/git/monkeyTest/monkeyTest.py", line 88, in start
    mkdirInit(devices, app, num)
  File "/home/cmd/workspace/git/monkeyTest/monkeyTest.py", line 54, in mkdirInit
    app[devices] = {"cpu": cpu, "men": men, "flow": flow, "battery": battery, "fps": fps, "header": get_phome(devices)}
  File "/home/cmd/workspace/git/monkeyTest/monkeyTest.py", line 38, in get_phome
    bg = BasePhoneMsg.get_phone_Kernel(devices)
  File "/home/cmd/workspace/git/monkeyTest/Base/BasePhoneMsg.py", line 66, in get_phone_Kernel
    pix = get_app_pix(devices)
  File "/home/cmd/workspace/git/monkeyTest/Base/BasePhoneMsg.py", line 62, in get_app_pix
    return  subprocess.check_output(cmd).split()[2].decode()
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'adb -s 45806625 shell wm size'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cmd/workspace/git/monkeyTest/monkeyTest.py", line 154, in <module>
    runnerPool()
  File "/home/cmd/workspace/git/monkeyTest/monkeyTest.py", line 77, in runnerPool
    pool.map(start, devices_Pool)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'adb -s 45806625 shell wm size'

Process finished with exit code 1

请问   如果想在ubuntu调通 该如何弄

**Comment by Louis-me** [comment]
还没有适配其他环境适配，暂时不会适配了，后续会打算脱离PC运行，到时候有空会一并处理适配问题，之前代码少了个Log文件夹，你在试试
