### ISSUE TITLE
虚拟器Genymotion 卡在此处

### ISSUE THREAD

**Issue by Archer456** [284772894/monkeyTest#9]
D:\workspace\git\monkeyTest>adb devices -l
List of devices attached
192.168.60.101:5555    device product:vbox86p model:Samsung_Galaxy_S7___7_1_0___API_25___1440x2560 device:vbox86p

D:\Python36\python3.exe D:/workspace/git/monkeyTest/monkeyTest.py
======================
*** liyu 2015-01-15***
***     v1.0.0     ***
======================
---------------------------
Checking adb port...
�ɹ�: ����ֹ PID Ϊ 11192 �Ľ��̡�
����: û���ҵ����� "11192"��
����: û���ҵ����� "11192"��
����: û���ҵ����� "18944"��
����: û���ҵ����� "14632"��
---------------------------
adb port has been released!
---------------------------
error: protocol fault (couldn't read status): Connection reset by peer
adb devices
adb -s * daemon not running. starting it now at tcp:5037 ** daemon started successfully *192.168.60.101:5555 shell wm size
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\workspace\git\monkeyTest\monkeyTest.py", line 88, in start
    mkdirInit(devices, app, num)
  File "D:\workspace\git\monkeyTest\monkeyTest.py", line 54, in mkdirInit
    app[devices] = {"cpu": cpu, "men": men, "flow": flow, "battery": battery, "fps": fps, "header": get_phome(devices)}
  File "D:\workspace\git\monkeyTest\monkeyTest.py", line 38, in get_phome
    bg = BasePhoneMsg.get_phone_Kernel(devices)
  File "D:\workspace\git\monkeyTest\Base\BasePhoneMsg.py", line 66, in get_phone_Kernel
    pix = get_app_pix(devices)
  File "D:\workspace\git\monkeyTest\Base\BasePhoneMsg.py", line 62, in get_app_pix
    return  subprocess.check_output(cmd).split()[2].decode()
  File "D:\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "D:\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'adb -s * daemon not running. starting it now at tcp:5037 ** daemon started successfully *192.168.60.101:5555 shell wm size' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/workspace/git/monkeyTest/monkeyTest.py", line 154, in <module>
    runnerPool()
  File "D:/workspace/git/monkeyTest/monkeyTest.py", line 77, in runnerPool
    pool.map(start, devices_Pool)
  File "D:\Python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command 'adb -s * daemon not running. starting it now at tcp:5037 ** daemon started successfully *192.168.60.101:5555 shell wm size' returned non-zero exit status 1.

Process finished with exit code 1

**Comment by Louis-me** [comment]
虚拟机没有试过，应该没问题，请问是什么操作系统，我只是测试了win

**Comment by Archer456** [comment]
win10 环境啊   python3.6.2   

模拟器
adb devices -l
List of devices attached
192.168.60.101:5555    device product:vbox86p model:Samsung_Galaxy_S7___7_1_0___API_25___1440x2560 device:vbox86p

目前更新工程后日志:
D:\Python36\python3.exe D:/workspace/git/monkeyTest/monkeyTest.py
======================
*** liyu 2015-01-15***
***     v1.0.0     ***
======================
---------------------------
Checking adb port...
�ɹ�: ����ֹ PID Ϊ 15248 �Ľ��̡�
* server not running *
adb devices
adb -s 192.168.60.101:5555 shell wm size
adb -s 192.168.60.101:5555 shell cat /proc/meminfo
adb -s 192.168.60.101:5555 shell cat /system/build.prop
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\workspace\git\monkeyTest\monkeyTest.py", line 88, in start
    mkdirInit(devices, app, num)
  File "D:\workspace\git\monkeyTest\monkeyTest.py", line 54, in mkdirInit
    app[devices] = {"cpu": cpu, "men": men, "flow": flow, "battery": battery, "fps": fps, "header": get_phome(devices)}
  File "D:\workspace\git\monkeyTest\monkeyTest.py", line 38, in get_phome
    bg = BasePhoneMsg.get_phone_Kernel(devices)
  File "D:\workspace\git\monkeyTest\Base\BasePhoneMsg.py", line 68, in get_phone_Kernel
    phone_msg = getModel(devices)
  File "D:\workspace\git\monkeyTest\Base\BasePhoneMsg.py", line 37, in getModel
    result["phone_name"] = re.findall("ro.product.model=(\S+)*", output, re.S)[0] # 手机名
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:/workspace/git/monkeyTest/monkeyTest.py", line 155, in <module>
    runnerPool()
  File "D:/workspace/git/monkeyTest/monkeyTest.py", line 77, in runnerPool
    pool.map(start, devices_Pool)
  File "D:\Python36\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
IndexError: list index out of range

Process finished with exit code 1
